spring:
  profiles:
    default: local
  jwt:
    header: Authorization
    secret: SSBsb3ZlIHlvdSwgYmFieSBhbmQgaWYgaXQncyBxdWl0ZSBhbHJpZ2h0DQpJIG5lZWQgeW91LCBiYWJ5IHRvIHdhcm0gdGhlIGxvbmVseSBuaWdodHMNCkkgbG92ZSB5b3UsIGJhYnksIHRydXN0IGluIG1lIHdoZW4gSSBzYXkNCk9oLCBwcmV0dHkgYmFieSwgZG9uJ3QgYnJpbmcgbWUgZG93biBJIHByYXkNCk9oLCBwcmV0dHkgYmFieSwgbm93IHRoYXQgSSd2ZSBmb3VuZCB5b3Ugc3RheQ0KTGV0IG1lIGxvdmUgeW91LCBiYWJ5LCBsZXQgbWUgbG92ZSB5b3U=
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/feely?serverTimezone=UTC&characterEncoding=UTF-8
    username: yalgo
    password: 1234

#cors.allow.method: GET, POST, PATCH, DELETE, OPTIONS

mybatis:
  mapper-locations: classpath:/mapper/*.xml


---
spring:
  config:
    activate:
      on-profile: prod

---
spring:
  config:
    activate:
      on-profile: local

  # Spring DataSource postgresql

