spring:
  profiles:
    default: local
  jwt:
    header: Authorization
    secret: eWFsZ29faXNfZnJlZQ==   # https://www.convertstring.com/ko/EncodeDecode/Base64Encode -> yalgo_is_free
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/feeely?serverTimezone=UTC&characterEncoding=UTF-8
    username: yalgo
    password: 1234

#cors.allow.method: GET, POST, PATCH, DELETE, OPTIONS

mybatis:
  mapper-locations: classpath:/mapper/*.xml


---
spring:
  config:
    activate:
      on-profile: prod

---
spring:
  config:
    activate:
      on-profile: local

  # Spring DataSource postgresql

